version: '3'

services:
  app:
    container_name: rwanda_serve
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn serve
    volumes:
      - .:/app
    ports:
      - 3000:8080