version: '3'

services:
  app:
    container_name: rwanda_account_app
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn serve
    privileged: true
    volumes:
      - .:/app
    ports:
      - 3000:8080